### ISSUE TITLE
程序运行没问题 但是点击抓包的launch崩溃，找不到类

### ISSUE THREAD

**Issue by laoziaichihebaodan** [lygttpod/AndroidMonitor#12]
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.lygttpod.monitor.ui.MonitorMainActivity" on path: DexPathList[[zip file "/data/app/~~ODzpq7fA8hPEWcFgb-ea5w==/com.zzmmc.doctor.test-_UB2d3sfA61nzaOxXLHHKw==/base.apk"],nativeLibraryDirectories=[/data/app/~~ODzpq7fA8hPEWcFgb-ea5w==/com.zzmmc.doctor.test-_UB2d3sfA61nzaOxXLHHKw==/lib/arm64, /data/app/~~ODzpq7fA8hPEWcFgb-ea5w==/com.zzmmc.doctor.test-_UB2d3sfA61nzaOxXLHHKw==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:218)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
        at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1273)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3658)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3935) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2288) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:210) 
        at android.os.Looper.loop(Looper.java:299) 
        at android.app.ActivityThread.main(ActivityThread.java:8291) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045) 
    	Suppressed: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/material/navigation/NavigationBarView$OnItemSelectedListener;
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        		... 17 more
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.material.navigation.NavigationBarView$OnItemSelectedListener" on path: DexPathList[[zip file "/data/app/~~ODzpq7fA8hPEWcFgb-ea5w==/com.zzmmc.doctor.test-_UB2d3sfA61nzaOxXLHHKw==/base.apk"],nativeLibraryDirectories=[/data/app/~~ODzpq7fA8hPEWcFgb-ea5w==/com.zzmmc.doctor.test-_UB2d3sfA61nzaOxXLHHKw==/lib/arm64, /data/app/~~ODzpq7fA8hPEWcFgb-ea5w==/com.zzmmc.doctor.test-_UB2d3sfA61nzaOxXLHHKw==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:218)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        		... 20 more

**Comment by laoziaichihebaodan** [comment]
使用0.0.6、0.0.7有这个问题，使用0.0.4版本没问题

**Comment by lygttpod** [comment]
@laoziaichihebaodan 
升级新版本试试
      
**monitor ---> 0.0.9**         
**monitor-plugin  ---> 0.0.2**
