### ISSUE TITLE
release包崩溃

### ISSUE THREAD

**Issue by JellyBrother** [lygttpod/AndroidMonitor#21]
2023-02-06 16:56:55.815 25575-25606/? E/CrashReport: --------------------------------------------------------------------------------------------
2023-02-06 16:56:55.824 25575-25575/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.inovance.palmhouse, PID: 25575
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/lygttpod/monitor/MonitorHelper;
        at okhttp3.OkHttpClient$Builder.<init>(Unknown Source:105)
        at okhttp3.OkHttpClient.<init>(Unknown Source:2)
        at com.inovance.palmhouse.base.net.RetrofitCreateHelper.initOkHttp(Unknown Source:6)

**Comment by lygttpod** [comment]
请使用最新版本在试一下
